### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Suburbanno** [TheAndroidMaster/Pasta-for-Spotify#19] opened 2016-12-20 14:15 UTC
![screenshot_2016-12-20-11-14-21](https://cloud.githubusercontent.com/assets/13632826/21353633/a8d0c6ca-c6a5-11e6-9a88-564a94a5c217.png)
]

**Comment by fennifith** [comment] 2016-12-20 14:18
Duplicate of #1

**Closed as completed by fennifith** 2016-12-20 14:18 UTC
Labels: duplicate
